-- 00012: Analyses-run idempotency key (Stage F5)
--
-- Adds a unique idempotency_key column on the `checks` table so that a
-- client retry of POST /api/analyses/run does not create a duplicate
-- check row. The api handler reads `Idempotency-Key` request header
-- (UUID v4 generated by client) and uses it as the column value.
--
-- Old rows have NULL idempotency_key — UNIQUE INDEX is partial so it
-- only enforces uniqueness for the new key-bearing rows.
--
-- The check on key length keeps obviously-malformed input out of the DB.

ALTER TABLE public.checks
  ADD COLUMN IF NOT EXISTS idempotency_key text
    CHECK (idempotency_key IS NULL OR (char_length(idempotency_key) BETWEEN 8 AND 128));

CREATE UNIQUE INDEX IF NOT EXISTS idx_checks_idempotency_key
  ON public.checks(user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;
